server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/whatsbot
    username: wbuser
    password: wbpass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: debug
