services:
  db:
    image: postgres:16
    container_name: wb-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - wb_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: wb-redis
    ports:
      - "6379:6379"

volumes:
  wb_pgdata:
